version: '2'
services:
  front-end:
    build: ./front-end
    networks:
      - back-end
    ports: 
      - 3000:3000
    env_file: ./front-end/.env
    depends_on:
      - "back-end"

  back-end:
    build: ./back-end
    networks:
      - back-end
    ports: 
      - 8000:8000
    env_file: ./back-end/.env


networks:
  back-end: