version: '3.9'
services:
  front-end:
    build: ./front-end
    container_name: front_end
    environment:
      - REACT_APP_API_URL=http://localhost:8000/
    networks:
      - back-end
    ports: 
      - 3000:3000
    depends_on:
      - "back-end"

  back-end:
    build: ./back-end
    container_name: back_end_and_data_base
    environment:
      - CLEARDB_DATABASE_URL=mysql://b619667ee0fd5c:809ec561@us-cdbr-east-05.cleardb.net/
      - heroku_2ecc86b13a5a13a?reconnect=true
      - HOST=us-cdbr-east-05.cleardb.net
      - USERNAME=b619667ee0fd5c
      - PASSWORD=809ec561
      - DATA_BASE=heroku_2ecc86b13a5a13a
      - PORT=8000
    networks:
      - back-end
    ports: 
      - 8000:8000


networks:
  back-end: