version: '1.29.2'
services:
  front-end:
    build: ./front-end
    networks:
      - back-end
    ports: 
      - 3000:3000
    env_file: .env
    depends_on:
      - "back-end"

  back-end:
    build: ./back-end
    networks:
      - back-end
    ports: 
      - 8000:8000
    env_file: .env


networks:
  back-end: